### ISSUE TITLE
schwere Waffe fehlt beim US Army Cal. 50 Team

### ISSUE THREAD

**Issue by Bellum45** [dstahlmann/cold-war-crisis#3]
Das 12,7mm MG des US Army Cal. 50 Team hat kein 'schwere Waffe' Sonderregel, wenn man es auf den Boden richtet.

**Comment by Anathema686** [comment]
Fix ist angewendet, Stand 07/10/24.

**Comment by Anathema686** [comment]
Fix ist angewendet, Stand 07/10/24.
