### ISSUE TITLE
Die Sprenggranate der Sowjet Union hat nicht Panzerbrechend

### ISSUE THREAD

**Issue by Bellum45** [dstahlmann/cold-war-crisis#33]
Die Sprenggranate der Sowjet Union hat nicht Panzerbrechend, ist das Absicht?

**Comment by dstahlmann** [comment]
Ich eröffne das nochmal. Wie hast du das jetzt gelöst @Anathema686?

**Comment by Bellum45** [comment]
Ich würde sagen, alle Sprenggranate der Sowjet Union haben jetzt Panzerbrechend.
