### ISSUE TITLE
Nur die US Pioniere haben Rauchgranaten

### ISSUE THREAD

**Issue by Bellum45** [dstahlmann/cold-war-crisis#38]
Ist es Absicht, dass nur die US Pioniere Rauchgranaten haben?

**Comment by dstahlmann** [comment]
Ich eröffne das nochmal. Wer sollte deiner Meinung nach alles Rauchgranaten haben @Bellum45?

**Comment by Bellum45** [comment]
Ich fande es nur merkwürdig, dass nur die Pioniere von dem USA Rauchgranaten haben. Darum habe ich es als Frage markiert.
